### ISSUE TITLE
Assign quantifiers - you should only be able to assign quantifiers once

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise_frontend#101]
Plus - what happens if endpoint is called two times in rapid succession, with the second call being done before first one has completed?

**Comment by mattyg** [comment]
There are a few potential bugs here:
1. assignQuantifiers fails part-way through
2. assignQuantifiers is called twice, before the first call has completed
3. assignQuantifiers is called twice, after the first call has completed

The risk is that via bugs or edge-cases we could end up with our database data in a "dirty" state. I.e. the data does not reflect our assumptions about it held throughout the application. 

I implemented a short-term workaround to bugs 2 & 3 in #222. It will at least help us catch more of these data integrity issues. That said, I think these possible bugs only arise because we are not enforcing our data integrity assumptions at the database + ORM layer.

**"Root" Solutions to potential bugs above**
1. Refactoring assignQuantifiers to execute all database writes in a single "transaction", and revert the entire transaction if it fails. 

Unfortunately mongodb only supports transactions when your database is setup with a replica set (i.e. we need 2-3 mongodb servers configured into a single replica set to use it's transaction feature). 

2. Refactor assignQuantifiers to execute as an asyncronous job in a queue, rather than during the http request-response cycle. The job queue system would handle reliably executing / retrying jobs. 

Upon calling /assignQuantifiers, the controller would simply add the job to the queue. The front-end would then poll a new endpoing assignQuantifersStatus to see the status of the job, and redirect the user when done. The job would check if it should be run, before running.

Job queue systems are very robust and designed for this exact problem of reliably ensuring a function get's executed, or retried, it's failure gets logged.

3. If we had our data assumptions enforced at the ORM + database layer, someone could call assignQuantifiers twice without any risk. The function would fail to write anything to the database and throw an error. If we wanted to improve that UX we could add a check that throws a user-friendly error message, but idk if it's necessary.
